= fress

fress is a toolkit for processing information with computers.

* Code docs: https://www.fress.io/fress[fress.io/fress]
* Repository: https://github.com/u0xee/fress[github.com/u0xee/fress]

== Welcome, Wayfarer!
This project is named _fress_ (as in "fresh fruit"). It is software (instructions for a computer) that
can be used to process information.

== What's here?
Here in this repository (these project files), you will find:

* Documentation sources in link:/doc[]
** Essay on the trees at link:/doc/story/forking-trees.adoc[]
   (better viewed online https://www.fress.io/story/forking-trees[forking trees])
** Images used in documentation in link:/doc/images[]
* Source code in link:/src[] (code docs viewed online https://www.fress.io/fress[fress.io/fress])
** The library root at link:/src/lib.rs[]
** The memory module's root at link:/src/memory/mod.rs[]
* Integration tests in link:/tests[]
** Benchmarks in link:/benches[]
* Example programs in link:/examples[]

== Things to do
You can read the source code and documentation sources, without any special tools.

If you want to run the code, you'll need to https://www.rust-lang.org/learn/get-started[install the Rust programming language].
After you have Rust installed, you can use the `cargo` program:

* `cargo help`
* `cargo build`
* `cargo test`
* `cargo bench`
* `cargo run --example basic` runs the example program link:/examples/basic.rs[]

== Building the website
Documentation sources are turned into the website using https://asciidoctor.org[Asciidoctor].
If you want to build the website yourself, you'll need to install it, and https://www.python.org[Python3].

Then you can run the script at link:/build_docs.py[], which runs `cargo doc` and `asciidoctor`.
http://linuxcommand.org/lc3_wss0010.php[Run the script] like this: `./build_docs.py`.

== License
Below, and in every source code file, you will find a license notice. Briefly:

* don't sue me
* don't remove the license notices
* don't steal my work (by claiming or implying you did it)

NOTE: You can copy, modify, and redistribute this work (build on top of my work),
as long as you make it clear that you are building on top of my work.

----
Copyright (c) Cole Frederick. All rights reserved.
The use and distribution terms for this software are covered by the
Eclipse Public License 1.0 (https://opensource.org/licenses/eclipse-1.0.php)
which can be found in the file epl-v10.html at the root of this distribution.
By using this software in any fashion, you are agreeing to be bound by the terms of this license.
You must not remove this notice, or any other, from this software.
----

