== Bibliography
:scholar: https://scholar.google.com/scholar_lookup?author=
:rfc: https://tools.ietf.org/html/rfc

// TODO add infoq, podcasts, Conf. presentations, languages
// advisers, Alexander Hulpke

[.big]
[cols="8*^"]
|===
| <<bib-a,A>> | <<bib-b,B>> | <<bib-c,C>>
| <<bib-d,D>> | <<bib-e,E>> | <<bib-f,F>>
| <<bib-g,G>> | <<bib-h,H>> | <<bib-i,Ĳ>>
| <<bib-k,K>> | <<bib-l,L>> | <<bib-m,M>>
| <<bib-n,N>> | <<bib-o,O>> | <<bib-p,P>>
| <<bib-r,Q>> | <<bib-r,R>> | <<bib-s,S>>
| <<bib-t,T>> | <<bib-u,U>> | <<bib-v,V>>
| <<bib-w,W>> | <<bib-y,Y>> | <<bib-y,Z>>
|===

[[bib-a]]
* [[[Ackerman-Memory]]] William *Ackerman* (1977) _A structure memory for data flow computers._
  Technical Report 186, MIT Cambridge Lab for Computer Science.
  {scholar}ackerman&title=structure+memory+data+flow+computers[search^]

* [[[VAL]]] William *Ackerman* and Jack *Dennis* (1979) _VAL: A Value-Oriented Algorithmic Language._
  Technical Report 218, MIT Cambridge Lab for Computer Science.
  {scholar}ackerman&title=val+value+oriented+algorithmic+language[search^]

* [[[Data-Flow-Languages]]] William *Ackerman* (1982) _Data flow languages._ Computer 15.2.
  {scholar}ackerman&title=Data+flow+languages[search^]

* [[[Ackerman-Thesis]]] William Beekley *Ackerman* (1984) _Efficient implementation of applicative languages._
  Doctoral thesis, Massachusetts Institute of Technology.
  {scholar}ackerman&title=efficient+implementation+applicative+languages[search^]

* [[[AVL-Tree]]] George *Adel'son-Vel'skii* and Evgenii *Landis* (1962)
  _An algorithm for organization of information._
  Doklady Akademii Nauk. Vol. 146, No. 2. Russian Academy of Sciences.
  {scholar}landis&title=an+algorithm+for+organization+of+information[search^]

* [[[Awk]]] Alfred *Aho*, Brian *Kernighan* and Peter *Weinberger* (1979)
  _[.caps]#Awk#: a pattern scanning and processing language._ Software Practice and Experience 9.4.
  {scholar}aho&title=awk+a+pattern+scanning+and+processing+language[search^]

* [[[Almeida]]] Paulo Sérgio *Almeida* (1997) _Balloon types: Controlling sharing of state in data types._
  Object-Oriented Programming, [.acro]#ECOOP#, Lecture Notes in Computer Science, Vol. 1241.
  Springer, Berlin, Heidelberg.
  https://link.springer.com/chapter/10.1007/BFb0053373[source^]

* [[[Appel-GC]]] Andrew *Appel* (1987) _Garbage collection can be faster than stack allocation._
  Information Processing Letters 25.4.
  {scholar}appel&title=garbage+collection+can+be+faster+than+stack+allocation[search^]

* [[[Appel-Consing]]] Andrew *Appel* and Marcelo *Conçalves* (1993) _Hash-consing garbage collection._
  Princeton University, Department of Computer Science.
  {scholar}appel&title=hash+consing+garbage+collection[search^]

* [[[LogicBlox]]] Molham *Aref* et al. (2015) _Design and implementation of the [.caps]#LogicBlox# system._
  Proc. of ACM [.acro]#SIGMOD# Intl. Conf. on Management of Data.
  {scholar}aref&title=design+and+implementation+of+the+logicblox+system[search^]

* [[[Armstrong-Thesis]]] Joe *Armstrong* (2003) _Making reliable distributed systems in the presence of software errors._
  Doctoral thesis, The Royal Institute of Technology, Stockholm, Sweden.
  http://erlang.org/download/armstrong_thesis_2003.pdf[source^]

* [[[Armstrong-Guide]]] Joe *Armstrong* (2018) _Computer Science: A Guide for the Perplexed._
  [.acro]#GOTO# Conf.

* [[[Aspinall-Hofmann]]] David *Aspinall* and Martin *Hofmann* (2002) _Another type system for in-place update._
  European Symposium on Programming. Springer, Berlin, Heidelberg.
  {scholar}aspinall&title=another+type+system[search^]

[[bib-b]]
* [[[FORTRAN]]] John *Backus* et al. (1957) _The [.acro]#FORTRAN# automatic coding system._
  Papers presented at the Western Joint Computer Conf., Techniques for Reliability. ACM.
  {scholar}backus&title=the+fortran+automatic+coding+system[search^]

* [[[ALGOL]]] John *Backus*, Friedrich *Bauer*, Julien *Green*, Charles *Katz*,
  John *McCarthy*, Peter *Naur* and Alan *Perlis* (1960)
  _Report on the algorithmic language [.acro]#ALGOL 60#._ Numerische Mathematik 2.1.
  {scholar}backus&title=report+on+the+algorithmic+language+algol[search^]

* [[[Backus-Semantics]]] John *Backus* (1973) _Programming language semantics and closed applicative languages._
  Proc. of [.ordn]#1st# Annual ACM [.acro]#SIGACT-SIGPLAN# symposium on Principles of Programming Languages. ACM.
  {scholar}backus&title=programming+language+semantics[search^]

* [[[Backus-Functional]]] John *Backus* (1978) _Can programming be liberated from the von Neumann style?
  A functional style and its algebra of programs._ 1977 ACM Turing Award Lecture, Comm. of ACM 21.8.
  https://dl.acm.org/citation.cfm?id=1283933[source^]

* [[[Bacon-GC]]] David *Bacon*, Perry *Cheng* and V. T. *Rajan* (2004)
  _A unified theory of garbage collection._ ACM [.acro]#SIGPLAN# Notices 39.10.
  {scholar}bacon&title=a+unified+theory+of+garbage+collection[search^]

* [[[Bagwell-Search]]] Phil *Bagwell* (2000) _Fast and Space-efficient Trie Searches._ Technical report, EPFL.
  {scholar}bagwell&title=fast+and+space+efficient+trie+searches[search^]

* [[[Ideal-Hash-Tree]]] Phil *Bagwell* (2001) _Ideal Hash Trees._ Technical report, EPFL.
  {scholar}bagwell&title=ideal+hash+trees[search^]

* [[[Bagwell-List]]] Phil *Bagwell* (2002) _Fast Functional Lists, Hash-Lists, Deques and Variable Length Arrays._
  Symposium on Implementation and Application of Functional Languages. Springer, Berlin, Heidelberg.
  {scholar}bagwell&title=fast+functional+lists[search^]

* [[[RRB-Tree]]] Phil *Bagwell* and Tiark *Rompf* (2011) _[.caps]#RRB-Trees#: Efficient Immutable Vectors._
  Technical Report [.acro]#EPFL-REPORT-169879#, Ecole Polytechnique Fédérale de Lausanne.
  {scholar}bagwell&title=rrb+trees+efficient+immutable+vectors[search^]

* [[[Baker-Processes]]] Henry G. *Baker* Jr. and Carl *Hewitt* (1977) _The incremental garbage collection of processes._
  ACM [.acro]#SIGPLAN# Notices 12.8.
  http://www.pipeline.com/~hbaker1/Futures.html[source^]

* [[[Baker-Real-Time]]] Henry G. *Baker* (1978) _List processing in real time on a serial computer._
  Comm. of ACM 21.4.
  {scholar}baker&title=list+processing+in+real+time+on+a+serial+computer[search^]

* [[[Baker-Unify]]] Henry G. *Baker* (1990) _Unify and conquer (Garbage, Updating, Aliasing) in Functional Languages._
  Proc. of ACM Conf. on LISP and Functional Programming.
  http://www.pipeline.com/~hbaker1/Share-Unify.html[source^]

* [[[Baker-Shallow]]] Henry G. *Baker* (1991) _Shallow binding makes functional arrays fast._
  ACM [.acro]#SIGPLAN# Notices 26.8.
  http://www.pipeline.com/~hbaker1/ShallowArrays.html[source^]

* [[[Baker-Linear]]] Henry G. *Baker* (1992) _Lively linear Lisp -- "Look ma, no garbage!"_
  ACM [.acro]#SIGPLAN# Notices 27.8.
  http://www.pipeline.com/~hbaker1/LinearLisp.html[source^]

* [[[Baker-Treadmill]]] Henry G. *Baker* (1992) _The treadmill: real-time garbage collection without motion sickness._
  ACM [.acro]#SIGPLAN# Notices 27.3.
  http://www.pipeline.com/~hbaker1/NoMotionGC.html[source^]

* [[[Baker-Equality]]] Henry G. *Baker* (1993) _Equal rights for functional objects or,
  the more things change, the more they are the same._ ACM [.acro]#SIGPLAN OOPS# Messenger 4.4.
  http://www.pipeline.com/~hbaker1/ObjectIdentity.html[source^]

* [[[Baker-Pointers]]] Henry G. *Baker* (1994) _Minimizing reference count updating with deferred and
  anchored pointers for functional data structures._ ACM [.acro]#SIGPLAN# Notices 29.9.
  http://www.pipeline.com/~hbaker1/LRefCounts.html[source^]

* [[[Baker-Use-Once]]] Henry G. *Baker* (1995) _"Use-once" variables and linear objects: storage management,
  reflection and multi-threading._ ACM [.acro]#SIGPLAN# Notices 30.1.
  http://www.pipeline.com/~hbaker1/Use1Var.html[source^]

* [[[Dataless-Programming]]] Robert *Balzer* (1967) _Dataless programming._
  Proc. of Fall Joint Computer Conf., ACM.
  {scholar}balzer&title=dataless+programming[search^]

* [[[Barth]]] Jeffrey *Barth* (1977) _Shifting garbage collection overhead to compile time._
  Comm. of ACM 20.7.
  {scholar}barth&title=shifting+garbage+collection+overhead+to+compile+time[search^]

* [[[Bawden-State]]] Alan *Bawden* (1988) _Analyzing the State Behavior of Programs._
  Working Paper 311, MIT Artificial Intelligence Lab.
  {scholar}bawden&title=analyzing+the+state+behavior+of+programs[search^]

* [[[Bawden-Thesis]]] Alan *Bawden* (1992) _Linear Graph Reduction: Confronting the Cost of Naming._
  Doctoral thesis, Adviser Gerald Jay *Sussman*, MIT.
  {scholar}bawden&title=linear+graph+reduction[search^]

* [[[Binary-B-tree]]] Rudolf *Bayer* (1971) _Binary B-trees for virtual memory._
  Proc. of ACM [.acro]#SIGFIDET# (now [.acro]#SIGMOD#) Workshop on Data Description, Access and Control.
  {scholar}bayer&title=binary+b+trees+for+virtual+memory[search^]

* [[[B-tree]]] Rudolf *Bayer* and Edward *McCreight* (1972)
  _Organization and Maintenance of Large Ordered Indices._ Acta Informatica 1.
  {scholar}bayer&title=organization+and+maintenance[search^]

* [[[Prefix-B-Tree]]] Rudolf *Bayer* and Karl *Unterauer* (1977) _Prefix B-trees._
  ACM Transactions on Database Systems 2.1.
  {scholar}bayer&title=prefix+b+trees[search^]

* [[[Bellin-Pi-Calculus]]] Gianluigi *Bellin* and Philip *Scott* (1994) _On the π-calculus and linear logic._
  Theoretical Computer Science 135.1.
  {scholar}bellin&title=on+the+π+calculus+and+linear+logic[search^]

* [[[HTTP-2]]] Mike *Belshe*, R. *Peon* and M. *Thomson* (2015)
  _HTTP/2 -- Hypertext Transfer Protocol Version 2._ RFC 7540, [.acro]#DOI 10.17487/RFC7540#. {rfc}7540[source^]

* [[[Bentley-McIlroy]]] Jon *Bentley* and Douglas *McIlroy* (1999) _Data compression using long common strings._
  Proc. of Data Compression Conf, IEEE.
  {scholar}bentley&title=data+compression+using+long+common+strings[search^]

* [[[Hypertext]]] Tim *Berners-Lee* (1989) _Information management: A proposal._ No. [.acro]#CERN-DD-89-001-OC#.
  {scholar}berners-lee&title=information+management+a+proposal[search^]

* [[[HTML]]] Tim *Berners-Lee* and D. *Connolly* (1995) _Hypertext Markup Language 2.0._
  RFC 1866, [.acro]#DOI 10.17487/RFC1866#. {rfc}1866[source^]

* [[[HTTP]]] Tim *Berners-Lee*, R. *Fielding* and H. *Frystyk* (1996) _HTTP/1.0 -- Hypertext Transfer Protocol._
  RFC 1945, [.acro]#DOI 10.17487/RFC1945#. {rfc}1945[source^]

* [[[URI]]] Tim *Berners-Lee*, R. *Fielding* and L. *Masinter* (2005)
  _URI: Uniform Resource Identifier._ STD 66, RFC 3986, [.acro]#DOI 10.17487/RFC3986#. {rfc}3986[source^]

* [[[MVCC]]] Philip *Bernstein* and Nathan *Goodman* (1983) _Multiversion concurrency control--theory and algorithms._
  ACM Transactions on Database Systems 8.4.
  {scholar}bernstein&title=multiversion+concurrency+control[search^]

* [[[Keccak-Reference]]] Guido *Bertoni*, Joan *Daemen*, Michaël *Peeters* and Gilles Van *Assche* (2011)
  _The [.caps]#Keccak# Reference._ Submission to NIST (Round 3) 13.
  https://keccak.team/files/Keccak-reference-3.0.pdf[source^]

* [[[Keccak]]] Guido *Bertoni* et al. (2013) _[.caps]#Keccak#._ Annual Intl. Conf. on the Theory and
  Applications of Cryptographic Techniques. Springer, Berlin, Heidelberg.
  https://keccak.team/keccak.html[source^]

* [[[Sakura]]] Guido *Bertoni* et al. (2014) _[.caps]#Sakura#: a flexible coding for tree hashing._
  Intl. Conf. on Applied Cryptography and Network Security. Springer, Cham.
  https://keccak.team/2013/sakura.html[source^]

* [[[Farfalle]]] Guido *Bertoni* et al. (2017) _[.caps]#Farfalle#: parallel permutation-based cryptography._
  IACR Transactions on Symmetric Cryptology.
  https://keccak.team/farfalle.html[source^]

* [[[Bird]]] Richard *Bird* (1989) _Lectures on constructive functional programming._
  Constructive Methods in Computing Science. Springer, Berlin, Heidelberg.
  {scholar}bird&title=lectures+on+constructive+functional+programming[search^]

* [[[Bloch-API]]] Joshua *Bloch* (2018) _A Brief, Opinionated History of the API._
  QCon 2018. https://www.youtube.com/watch?v=LzMp6uQbmns[source^]

* [[[Bloss]]] Adrienne *Bloss* (1989) _Update analysis and the efficient implementation of functional aggregates._
  Proc. of [.ordn]#4th# Intl. Conf. on Functional Programming Languages and Computer Architecture, ACM.
  {scholar}bloss&title=update+analysis+and+the+efficient+implementation+of+functional+aggregates[search^]

* [[[Boehm-Collector]]] Hans-Juergen *Boehm* and Mark *Weiser* (1988)
  _Garbage collection in an uncooperative environment._
  Software Practice and Experience 18.9.
  {scholar}boehm&title=garbage+collection+in+an+uncooperative+environment[search^]

* [[[Bohm-Single]]] Wim *Böhm* et al. (2002)
  _Mapping a single assignment programming language to reconfigurable systems._
  The Journal of Supercomputing 21.2.
  {scholar}bloss&title=mapping+a+single+assignment+programming+language+to+reconfigurable+systems[search^]

* [[[Slab-Allocator]]] Jeff *Bonwick* (1994) _The slab allocator: An object-caching kernel memory allocator._
  [.acro]#USENIX# Summer Vol. 16.
  {scholar}bonwick&title=the+slab+allocator[search^]

* [[[ZFS]]] Jeff *Bonwick*, Matt *Ahrens*, Val *Henson*, Mark *Maybee* and Mark *Shellenbaum* (2003)
  _The Zettabyte File System._
  Proc. of [.ordn]#2nd# [.acro]#USENIX# Conf. on File and Storage Technologies Vol. 215.
  {scholar}bonwick&title=the+zettabyte+file+system[search^]

* [[[Boyland-Capabilities]]] John *Boyland*, James *Noble* and William *Retert* (2001)
  _Capabilities for sharing._ European Conf. on Object-Oriented Programming. Springer, Berlin, Heidelberg.
  {scholar}boyland&title=capabilities+for+sharing[search^]

* [[[Boyland-Permissions]]] John *Boyland* (2003) _Checking interference with fractional permissions._
  Intl. Static Analysis Symposium. Springer, Berlin, Heidelberg.
  {scholar}boyland&title=checking+interference+with+fractional+permissions[search^]

* [[[JSON]]] Tim *Bray* (2017) _JSON: The JavaScript Object Notation Data Interchange Format._
  STD 90, RFC 8259, [.acro]#DOI 10.17487/RFC8259#. {rfc}8259[source^]

* [[[Brent]]] Richard *Brent* and Paul *Zimmermann* (2010) _Modern computer arithmetic._
  Cambridge University Press.
  https://www.google.com/books/edition/Modern_Computer_Arithmetic/-8wuH5AwbwMC[search^]

* [[[Brodal]]] Gerth Stølting *Brodal* et al. (2012) _Fully persistent B-trees._
  Proc. of [.ordn]#23rd# annual [.acro]#ACM-SIAM# symposium on Discrete Algorithms.
  Society for Industrial and Applied Mathematics.
  {scholar}brodal&title=fully+persistent+b+trees[search^]

* [[[Brooks-Music]]] Frederick *Brooks* et al. (1957) _An experiment in musical composition._
  IRE Transactions on Electronic Computers 3.
  {scholar}brooks&title=an+experiment+in+musical+composition[search^]

* [[[Man-Month]]] Frederick *Brooks* (1975) _The Mythical Man-Month: Essays on Software Engineering._
  Addison-Wesley, Reading MA.
  https://www.google.com/books/edition/The_Mythical_Man_Month/Yq35BY5Fk3gC[search^]

* [[[No-Silver-Bullet]]] Frederick *Brooks* (1987) _No Silver Bullet: Essence and Accidents of Software Engineering._
  IEEE Computer 20.4.
  {scholar}brooks&title=no+silver+bullet[search^]

* [[[Brooks-Compiler]]] Rodney *Brooks*, Richard *Gabriel* and Guy *Steele* (1982)
  _An optimizing compiler for lexically scoped [.acro]#LISP#._ ACM [.acro]#SIGPLAN# Notices 17.6.
  {scholar}brooks&title=an+optimizing+compiler+for+lexically+scoped+lisp[search^]

* [[[Clean]]] Tom *Brus* et al (1987) _Clean: a Language for Functional Graph Rewriting._
  Conf. on Functional Languages and Computer Architecture. Springer, Berlin, Heidelberg.
  {scholar}brus&title=clean+a+language+for+functional+graph+rewriting[search^]

* [[[Burger-Print]]] Robert *Burger* and R. Kent *Dybvig* (1996) _Printing floating-point numbers quickly and accurately._
  ACM [.acro]#SIGPLAN# Notices 31.5.
  {scholar}burger&title=printing+floating+point+numbers+quickly+and+accurately[search^]

* [[[Burrows-Wheeler]]] Michael *Burrows* and David *Wheeler* (1994)
  _A block-sorting lossless data compression algorithm._ SRC Research Report 124.
  {scholar}burrows&title=a+block+sorting+lossless+data+compression+algorithm[search^]

[[bib-c]]
* [[[Cann-Oldehoeft]]] David *Cann* and Rodney *Oldehoeft* (1988)
  _Reference count and copy elimination for parallel applicative computing._
  Technical Report [.acro]#CS-88-129#. Colorado State University, Fort Collins CO.
  {scholar}cann&title=reference+count+and+copy+elimination+for+parallel+applicative+computing[search^]

* [[[Cann-Thesis]]] David C. *Cann* (1989) _Compilation Techniques for High-performance Applicative Computation._
  Doctoral thesis, Colorado State University, Fort Collins CO.
  {scholar}cann&title=compilation+techniques+for+high+performance+applicative+computation[search^]

* [[[Cantrill-Bonwick]]] Bryan *Cantrill* and Jeff *Bonwick* (2008) _Real-world concurrency._
  Comm. of ACM 51.11.
  {scholar}cantrill&title=real+world+concurrency[search^]

* [[[DTrace]]] Bryan *Cantrill*, Michael *Shapiro* and Adam *Leventhal* (2004)
  _Dynamic Instrumentation of Production Systems._ [.acro]#USENIX# Annual Technical Conf.
  {scholar}cantrill&title=dynamic+instrumentation+of+production+systems[search^] -
  http://dtrace.org/blogs/about/[dtrace.org^]

* [[[Linda]]] Nicholas *Carriero* and David *Gelernter* (1989) _[.caps]#Linda# in context._
  Comm. of ACM 32.4.
  {scholar}carriero&title=linda+in+context[search^]

* [[[Carruth-No-Zero-Cost]]] Chandler *Carruth* (2019) _There Are No Zero-Cost Abstractions._
  CppCon 2019. https://www.youtube.com/watch?v=rHIkrotSwcc[source^]

* [[[SAL]]] James *Celoni* and John *Hennessy* (1983) _[.acro]#SAL#: A Single Assignment Language for Parallel Algorithms._
  Technical Report [.caps]#CLaSSic-83-01#, Stanford University.
  {scholar}celoni&title=sal+a+single+assignment+language[search^]

* [[[ASCII]]] Vint *Cerf* (1969) _[.acro]#ASCII# format for network interchange._
  STD 80, RFC 20, [.acro]#DOI 10.17487/RFC0020#. {rfc}20[source^]

* [[[Ceri-Datalog]]] Stefano *Ceri*, Georg *Gottlob* and Letizia *Tanca* (1989)
  _What you always wanted to know about [.caps]#Datalog# (and never dared to ask)._
  IEEE transactions on Knowledge and Data Engineering 1.1.
  {scholar}ceri&title=what+you+always+wanted+to+know+about+datalog[search^]

* [[[Chirimar]]] Jawahar *Chirimar*, Carl *Gunter* and Jon *Riecke* (1996)
  _Reference counting as a computational interpretation of linear logic._
  Journal of Functional Programming 6.2.
  {scholar}chirimar&title=reference+counting+as+a+computational+interpretation[search^]

* [[[Chuang]]] Tyng-Ruey *Chuang* (1992) _Fully persistent arrays for efficient incremental updates and voluminous reads._
  European Symposium on Programming. Springer, Berlin, Heidelberg.
  {scholar}chuang&title=fully+persistent+arrays+for+efficient+incremental+updates[search^]

* [[[Clarke-Ownership]]] David *Clarke*, John *Potter* and James *Noble* (1998)
  _Ownership Types for Flexible Alias Protection._ ACM [.acro]#SIGPLAN# Notices 33.10.
  {scholar}clarke&title=ownership+types+for+flexible+alias+protection[search^]

* [[[Clarke-Thesis]]] David *Clarke* (2001) _Object ownership and containment._
  Doctoral thesis, University of New South Wales, Australia.
  {scholar}clarke&title=object+ownership+and+containment[search^]

* [[[Clebsch]]] Sylvan *Clebsch* et al. (2015)
  _Ownership and reference counting based garbage collection in the actor world._
  [.acro]#ICOOOLPS# ACM.
  {scholar}clebsch&title=ownership+and+reference+counting+based+garbage+collection[search^]

* [[[Click-Hardware]]] Cliff *Click* (2009) _A Crash Course in Modern Hardware._
  Presented at JVM Languages Summit.
  https://www.infoq.com/presentations/click-crash-course-modern-hardware[source^]

* [[[Clinger-Continuation]]] William *Clinger*, Anne *Hartheimer* and Eric *Ost* (1988)
  _Implementation Strategies for Continuations._
  Proc. of ACM Conf. on LISP and Functional Programming.
  {scholar}clinger&title=implementation+strategies+for+continuations[search^]

* [[[Clinger-Read]]] William *Clinger* (1990) _How to read floating point numbers accurately._ Comm. of ACM 25.6.
  {scholar}clinger&title=how+to+read+floating+point+numbers+accurately[search^]

* [[[Collins]]] George *Collins* (1960) _A Method for Overlapping and Erasure of Lists._
  Comm. of ACM 3.12.
  {scholar}collins&title=a+method+for+overlapping+and+erasure+of+lists[search^]

* [[[Comer]]] Douglas *Comer* (1979) _The Ubiquitous B-tree._ ACM Computing Surveys 11.2.
  {scholar}comer&title=the+ubiquitous+b+tree[search^]

* [[[Coroutine]]] Melvin *Conway* (1963) _Design of a separable transition-diagram compiler._
  Comm. of ACM 6.7.
  {scholar}conway&title=design+of+a+separable+transition+diagram+compiler[search^]

* [[[Corbato]]] Fernando *Corbató* (1991) _On Building Systems That Will Fail._
  1990 ACM Turing Award Lecture, Comm. of ACM 34.9.
  {scholar}corbato&title=on+building+systems+that+will+fail[search^]

* [[[CLRS]]] Thomas *Cormen*, Charles *Leiserson*, Ronald *Rivest* and Clifford *Stein* (2009)
  _Introduction to Algorithms._ MIT Press.
  https://www.google.com/books/edition/Introduction_to_Algorithms/aefUBQAAQBAJ[search^]

* [[[Culik]]] Karel *Čulík* II, Thomas *Ottmann* and Derick *Wood* (1981) _Dense multiway trees._
  ACM Transactions on Database Systems 6.3.
  {scholar}culik&title=dense+multiway+trees[search^]

[[bib-d]]
* [[[Xoodoo]]] Joan *Daemen* et al. (2018) _[.caps]#Xoodoo# cookbook._
  IACR Cryptology ePrint Archive: 767.
  {scholar}daemen&title=xoodoo+cookbook[search^]

* [[[SIMULA]]] Ole-Johan *Dahl* and Kristen *Nygaard* (1966)
  _[.acro]#SIMULA#: an [.acro]##ALGOL##-based simulation language._
  Comm. of ACM 9.9.
  {scholar}dahl&title=simula+an+algol+based+simulation+language[search^]

* [[[Structured-Programming]]] Ole-Johan *Dahl*, Edsger *Dijkstra* and Tony *Hoare* (1972)
  _Structured Programming._ Academic Press Ltd.
  {scholar}dahl&title=structured+programming[search^]

* [[[Tail-at-Scale]]] Jeffrey *Dean* and Luiz André *Barroso* (2013) _The Tail at Scale._
  Comm. of ACM 56.2.
  {scholar}dean&title=the+tail+at+scale[search^]

* [[[Working-Set]]] Peter *Denning* (1967) _The working set model for program behavior._
  Proc. of [.ordn]#1st# ACM symposium on Operating System Principles.
  {scholar}denning&title=the+working+set+model+for+program+behavior[search^]

* [[[Virtual-Memory]]] Peter *Denning* (1970) _Virtual memory._ ACM Computing Surveys 2.3.
  {scholar}denning&title=virtual+memory[search^]

* [[[Dennis]]] Jack *Dennis* (1974) _First version of a data flow procedure language._
  Programming Symposium. Springer, Berlin, Heidelberg.
  {scholar}denning&title=first+version+of+a+data+flow+procedure+language[search^]

* [[[ZLIB]]] Peter *Deutsch* and Jean-Loup *Gailly* (1996)
  _[.acro]#ZLIB# Compressed Data Format Specification version 3.3._
  RFC 1950, [.acro]#DOI 10.17487/RFC1950#. {rfc}1950[source^]

* [[[DEFLATE]]] Peter *Deutsch* (1996) _[.acro]#DEFLATE# Compressed Data Format Specification version 1.3._
  RFC 1951, [.acro]#DOI 10.17487/RFC1951#. {rfc}1951[source^]

* [[[GZIP]]] Peter *Deutsch* (1996) _[.acro]#GZIP# file format specification version 4.3._
  RFC 1952, [.acro]#DOI 10.17487/RFC1952#. {rfc}1952[source^]

* [[[Dijkstra-CSP]]] Edsger *Dijkstra* (1968) _Cooperating sequential processes._
  The Origin of Concurrent Programming. Springer, New York NY.
  {scholar}dijkstra&title=cooperating+sequential+processes[search^]

* [[[Humble-Programmer]]] Edsger *Dijkstra* (1972) _The humble programmer._ Comm. of ACM 15.10.
  {scholar}dijkstra&title=the+humble+programmer[search^]

* [[[Dobkin-Munro]]] David *Dobkin* and J. Ian *Munro* (1980) _Efficient uses of the past._
  [.ordn]#21st# Symposium on Foundations of Computer Science, IEEE.
  {scholar}dobkin&title=efficient+uses+of+the+past[search^]
+
"... an AVL-tree of AVL-trees"

* [[[Domani-GC]]] Tamar *Domani* et al. (2001) _Implementing an on-the-fly garbage collector for Java._
  ACM [.acro]#SIGPLAN# Notices 36.1.
  {scholar}domani&title=implementing+an+on+the+fly+garbage+collector+for+java[search^]

* [[[Downey]]] Allen *Downey* (2007) _Generating Pseudo-random Floating-Point Values._
  {scholar}downey&title=generating+pseudo+random+floating+point+values[search^]

* [[[Driscoll-Thesis]]] James R. *Driscoll* (1986)
  _The Diameter of Permutation Groups--Fully Persistent Search Trees._ Doctoral thesis, Carnegie-Mellon University.
  {scholar}driscoll&title=the+diameter+of+permutation+groups+fully+persistent+search+trees[search^]

* [[[Persistent-Data-Structures]]] James *Driscoll*, Neil *Sarnak*, Daniel *Sleator* and Robert *Tarjan* (1989)
  _Making data structures persistent._ Journal of Computer and System Sciences 38.1.
  {scholar}driscoll&title=making+data+structures+persistent[search^]

* [[[Driscoll-List]]] James *Driscoll*, Daniel *Sleator* and Robert *Tarjan* (1994)
  _Fully persistent lists with catenation._ Journal of ACM 41.5.
  {scholar}driscoll&title=fully+persistent+lists+with+catenation[search^]

[[bib-e]]
* [[[SHA]]] D. *Eastlake* [.ordn]#3rd# and T. *Hansen* (2011) _US Secure Hash Algorithms._
  RFC 6234, [.acro]#DOI 10.17487/RFC6234#. {rfc}6234[source^]

* [[[Easton]]] Malcolm *Easton* (1986) _Key-sequence data sets on indelible storage._
  IBM Journal of R&D 30.3.
  {scholar}easton&title=key+sequence+data+sets+on+indelible+storage[search^]

[[bib-f]]
* [[[Extendible-Hashing]]] Ronald *Fagin* et al. (1979) _Extendible Hashing: A Fast Access Method for Dynamic Files._
  ACM Transactions on Database Systems 4.3.
  {scholar}fagin&title=extendible+hashing+a+fast+access+method+for+dynamic+files[search^]

* [[[Fahndrich-DeLine]]] Manuel *Fahndrich* and Robert *DeLine* (2002)
  _Adoption and focus: Practical linear types for imperative programming._ ACM [.acro]#SIGPLAN# Notices 37.5.
  {scholar}fahndrich&title=adoption+and+focus+practical+linear+types[search^]

* [[[Feeley-Lapalme]]] Marc *Feeley* and Guy *Lapalme* (1992)
  _Closure generation based on viewing lambda as epsilon plus compile._ Computer Languages 17.4.
  {scholar}feeley&title=closure+generation+based+on+viewing+lambda+as+epsilon[search^]

* [[[Feynman]]] Richard *Feynman* (1986) _Quantum mechanical computers._ Foundations of Physics 16.6.
  {scholar}feynman&title=quantum+mechanical+computers[search^]

* [[[SHA-3]]] FIPS-202 (2015) _SHA-3 standard: Permutation-based hash and extendable-output functions._
  NIST Publication, US Dept. of Commerce.
  https://www.nist.gov/itl/current-fips[source^]

* [[[Fitzgerald-Oldehoeft]]] Steven *Fitzgerald* and Rodney *Oldehoeft* (1996)
  _Update-in-place analysis for true multidimensional arrays._ Scientific Programming 5.2.
  {scholar}fitzgerald&title=update+in+place+analysis+for+true+multidimensional+arrays[search^]

* [[[Flajolet-Sedgewick]]] Philippe *Flajolet* and Robert *Sedgewick* (1986) _Digital search trees revisited._
  SIAM Journal on Computing 15.3.
  {scholar}flajolet&title=digital+search+trees+revisited[search^]

* [[[Floyd-Paradigms]]] Robert *Floyd* (1979) _The paradigms of programming._
  1978 ACM Turing Award Lecture, Comm. of ACM 22.8.
  {scholar}floyd&title=the+paradigms+of+programming[search^]

* [[[Trie]]] Edward *Fredkin* (1960) _Trie memory._ Comm. of ACM 3.9.
  {scholar}fredkin&title=trie+memory[search^]

* [[[Friedman-Combination]]] Daniel *Friedman* and David *Wise* (1978) _Functional combination._
  Computer Languages 3.1.
  {scholar}friedman&title=functional+combination[search^]

* [[[Friedman-Applicative]]] Daniel *Friedman* and David *Wise* (1978)
  _Aspects of applicative programming for parallel processing._ IEEE Transactions on Computers 4.
  {scholar}friedman&title=aspects+of+applicative+programming+for+parallel+processing[search^]

[[bib-g]]
* [[[GoF]]] Erich *Gamma*, John *Vlissides*, Richard *Helm* and Ralph *Johnson* (1994)
  _Design Patterns: elements of reusable object-oriented software._ Addison-Wesley, Reading MA.
  {scholar}gamma&title=design+patterns+elements+of+reusable+object+oriented+software[search^]

* [[[Sisal]]] Jean-Luc *Gaudiot*, Wim *Böhm*, Walid *Najjar*, Tom *DeBoni*, John *Feo* and Patrick *Miller* (1997)
  _The Sisal model of functional programming and its implementation._
  Proc. of IEEE Intl. Symposium on Parallel Algorithms Architecture Synthesis.
  {scholar}gaudiot&title=the+sisal+model+of+functional+programming[search^]

* [[[Sisal-Real-World]]] Jean-Luc *Gaudiot*, Tom *DeBoni*, John *Feo*,
  Wim *Böhm*, Walid *Najjar* and Patrick *Miller* (2001)
  _The Sisal project: Real world functional programming._
  In Compiler Optimizations for Scalable Parallel Systems. Springer, Berlin, Heidelberg.
  {scholar}gaudiot&title=the+sisal+project+real+world+functional+programming[search^]

* [[[Gay-Rounded]]] David *Gay* (1990) _Correctly rounded binary-decimal and decimal-binary conversions._
  Numerical Analysis Manuscript 90-10.
  {scholar}gay&title=correctly+rounded+binary+decimal+and+decimal+binary+conversion[search^]

* [[[Gelernter]]] Herbert *Gelernter*, J. R. *Hansen* and Carl *Gerberich* (1960)
  _A [.acro]##FORTRAN##-compiled list-processing language._ Journal of ACM 7.2.
  {scholar}gelernter&title=a+fortran+compiled+list+processing+language[search^]

* [[[Gharachorloo]]] Kourosh *Gharachorloo*, Vivek *Sarkar* and John *Hennessy* (1988)
  _A simple and efficient implementation approach for single assignment languages._
  Proc. of ACM Conf. on LISP and Functional Programming.
  {scholar}gharachorloo&title=a+simple+and+efficient+implementation+approach+for+single+assignment+languages[search^]

* [[[Girard]]] Jean-Yves *Girard* (1987) _Linear logic._ Theoretical Computer Science 50.1.
  {scholar}girard&title=linear+logic[search^]

* [[[Smalltalk]]] Adele *Goldberg* and Alan *Kay* (1976) _[.caps]##Smalltalk##-72 Instruction Manual._
  Palo Alto, Xerox Corporation.
  {scholar}goldberg&title=smalltalk+72+instruction+manual[search^]

* [[[Goldberg-Generational]]] Benjamin *Goldberg* (1989)
  _Generational reference counting: A reduced-communication distributed storage reclamation scheme._
  ACM [.acro]#SIGPLAN# Notices 24.7.
  {scholar}goldberg&title=generational+reference+counting[search^]

* [[[ENIAC]]] Herman *Goldstine* and Adele *Goldstine* (1946)
  _The electronic numerical integrator and computer [.acro]#ENIAC#._
  Mathematics of Computation 2.15.
  {scholar}goldstine&title=the+electronic+numerical+integrator+and+computer[search^]

* [[[Gopinath-Thesis]]] K. *Gopinath* (1988) _Copy Elimination in Single Assignment Languages._
  Doctoral thesis, Stanford University.
  {scholar}gopinath&title=copy+elimination+in+single+assignment+languages[search^]

* [[[Gopinath-Copy]]] K. *Gopinath* and John *Hennessy* (1989) _Copy elimination in functional languages._
  Proc. of [.ordn]#16th# ACM [.acro]#SIGPLAN-SIGACT# symposium on Principles of Programming Languages.
  {scholar}gopinath&title=copy+elimination+in+functional+languages[search^]

* [[[Goto-Monocopy]]] Eiichi *Goto* (1974) _Monocopy and associative algorithms in an extended lisp._
  Technical Report [.acro]#TR74-03#, University of Tokyo.
  {scholar}goto&title=monocopy+and+associative+algorithms[search^]

* [[[Goubault]]] Jean *Goubault* (1994)
  _Implementing functional languages with fast equality, sets and maps: an exercise in hash consing._
  Journées Francophones des Langages Applicatifs.
  {scholar}goubault&title=implementing+functional+languages+with+fast+equality[search^]

* [[[Red-Black-Tree]]] Leo *Guibas* and Robert *Sedgewick* (1978) _A dichromatic framework for balanced trees._
  [.ordn]#19th# Annual Symposium on Foundations of Computer Science, IEEE.
  {scholar}guibas&title=a+dichromatic+framework+for+balanced+trees[search^]

* [[[Gupta]]] Anoop *Gupta*, John *Hennessy*, Kourosh *Gharachorloo*, Todd *Mowry* and Wolf-Dietrich *Weber* (1991)
  _Comparative evaluation of latency reducing and tolerating techniques._
  ACM [.acro]#SIGARCH# Computer Architecture News 19.3.
  {scholar}gupta&title=comparative+evaluation+of+latency+reducing+and+tolerating+techniques[search^]

* [[[Guzman]]] Juan Carlos *Guzman* (1993) _On expressing the mutation of state in a functional programming language._
  Doctoral thesis, Adviser Paul *Hudak*, Yale University.
  {scholar}guzman&title=on+expressing+the+mutation+of+state+in+a+functional+programming+language[search^]

[[bib-h]]
* [[[Haller]]] Philipp *Haller* and Martin *Odersky* (2010) _Capabilities for Uniqueness and Borrowing._
  European Conf. on Object Oriented Programming. Springer, Berlin, Heidelberg.
  {scholar}haller&title=capabilities+for+uniqueness+and+borrowing[search^]

* [[[Fressian]]] Stuart *Halloway* (2012) _[.caps]#Fressian# extensible binary data notation._
  http://fressian.org[fressian.org^]

* [[[Halloway-Debugging]]] Stuart *Halloway* (2015) _Debugging with the Scientific Method._
  [.caps]#Clojure# Conj. 50 mins, https://youtu.be/FihU5JxmnBg[watch^].

* [[[Hederman]]] Lucy Mary *Hederman* (1989) _Compile time garbage collection using reference count analysis._
  Doctoral thesis, Adviser Hans-Juergen *Boehm*, Rice University.
  {scholar}hederman&title=compile+time+garbage+collection[search^]

* [[[Held-Carlis]]] James *Held* and John *Carlis* (1989) _The applicative data model._
  Information Sciences 49.1-3.
  {scholar}held&title=the+applicative+data+model[search^]

* [[[Hewitt-Baker]]] Carl *Hewitt* and Henry G. *Baker* (1977) _Laws for Communicating Parallel Processes._
  Working Paper 134A, MIT Artificial Intelligence Lab.
  {scholar}hewitt&title=laws+for+communicating+parallel+processes[search^]

* [[[Clojure]]] Rich *Hickey* (2007) _The [.caps]#Clojure# Programming Language._
  https://clojure.org[clojure.org^] - https://en.wikipedia.org/wiki/Clojure[wiki^]

* [[[Hickey-Managed-References]]] Rich *Hickey* (2009) _Persistent Data Structures and Managed References._
  QCon. 60 mins,  https://www.infoq.com/presentations/Value-Identity-State-Rich-Hickey/[watch^].

* [[[Hickey-There-Yet]]] Rich *Hickey* (2009) _Are We There Yet?_
  Keynote speech, JVM Languages Summit.
  70 mins, https://www.infoq.com/presentations/Are-We-There-Yet-Rich-Hickey/[watch^].

* [[[Simple-Made-Easy]]] Rich *Hickey* (2011) _Simple Made Easy._
  Strange Loop. 60 mins, https://www.infoq.com/presentations/Simple-Made-Easy/[watch^].
  Keynote speech, Rails Conf. 2012. 40 mins, https://youtu.be/rI8tNMsozo0[watch^].

* [[[Value-of-Values]]] Rich *Hickey* (2012) _The Value of Values._
  Keynote speech, JaxConf. 30 mins, https://youtu.be/-6BsiVyC1kM[watch^].
  GOTO Conf. Copenhagen. 60 mins, https://www.infoq.com/presentations/Value-Values/[watch^].

* [[[edn]]] Rich *Hickey* (2012) _The [.caps]#edn# extensible data notation._
  http://edn-format.org[edn-format.org^]

* [[[Database-as-a-Value]]] Rich *Hickey* (2012) _The Database as a Value._
  QCon London. 60 mins, https://www.infoq.com/presentations/Datomic-Database-Value/[watch^].

* [[[Language-of-the-System]]] Rich *Hickey* (2012) _The Language of the System._
  [.caps]#Clojure# Conj. 60 mins, https://youtu.be/ROor6_NGIWU[watch^].

* [[[Hickey-Made]]] Rich *Hickey* (2015) _[.caps]#Clojure#, Made Simple._
  JavaOne. 60 mins, https://youtu.be/VSdnJDO-xdg[watch^].

* [[[Effective-Programs]]] Rich *Hickey* (2017) _Effective Programs--10 Years of [.caps]#Clojure#._
  [.caps]#Clojure# Conj. 80 mins, https://youtu.be/2V1FtfBDsLU[watch^].

* [[[Hickey-Clark]]] Rich *Hickey* (2018) Interview with Joy *Clark*.
  [.caps]#CaSE# Podcast.
  60 mins, https://www.case-podcast.org/20-problem-solving-and-clojure-19-with-rich-hickey[listen^].

* [[[SQLite]]] D. Richard *Hipp* (2000) _[.caps]#SQLite# C library._
  Database engine as an in-process library.
  https://sqlite.org[sqlite.org^]. 60 mins (2015), https://youtu.be/Jib2AmRb_rk[watch^].

* [[[Fossil]]] D. Richard *Hipp* (2006) _[.caps]#Fossil# software configuration management._
  Programmer's tool for distributed (backup, history, and coordination), built on [.caps]#SQLite#.
  https://fossil-scm.org[fossil-scm.org^]. SouthEast LinuxFest, 60 mins (2011), https://youtu.be/-ceEWWqaVsI[watch^].

* [[[Quicksort]]] Charles Antony Richard *Hoare* (1962) _[.caps]#Quicksort#._ The Computer Journal 5.1.
  {scholar}hoare&title=quicksort[search^]

* [[[Hoare-Axiomatic]]] Tony *Hoare* (1969) _An axiomatic basis for computer programming._
  Comm. of ACM 12.10.
  {scholar}hoare&title=an+axiomatic+basis+for+computer+programming[search^]

* [[[Hoare-Design]]] Tony *Hoare* (1973) _Hints on programming language design._
  Report [.acro]#STAN-CS-73-403#, Dept. of Computer Science, Stanford University.
  {scholar}hoare&title=hints+on+programming+language+design[search^]

* [[[CSP]]] Tony *Hoare* (1978) _Communicating sequential processes._
  The Origin of Concurrent Programming. Springer, New York NY.
  {scholar}hoare&title=communicating+sequential+processes[search^]

* [[[Hoare-Emperor]]] Tony *Hoare* (1981) _The Emperor's Old Clothes._
  Comm. of ACM 24.2.
  {scholar}hoare&title=the+emperors+old+clothes[search^]

* [[[Hofmann]]] Martin *Hofmann* (2000) _A type system for bounded space and functional in-place update._
  European Symposium on Programming. Springer, Berlin, Heidelberg.
  {scholar}hofmann&title=a+type+system+for+bounded+space+and+functional+in+place+update[search^]

* [[[Holloway-Survey]]] Michael *Holloway* (1986) _A survey of functional programming language principles._
  Technical Memo [.acro]#89019#, Langley Research Center [.acro]#NASA#, Hampton VA.
  {scholar}holloway&title=a+survey+of+functional+programming+language+principles[search^]

* [[[Hudak-Distributed]]] Paul *Hudak* and Robert *Keller* (1982)
  _Garbage collection and task deletion in distributed applicative processing systems._
  Proc. of ACM symposium on LISP and Functional Programming.
  {scholar}hudak&title=garbage+collection+and+task+deletion+in+distributed+applicative+processing[search^]

* [[[Hudak-Aggregate-Update]]] Paul *Hudak* and Adrienne *Bloss* (1985)
  _The aggregate update problem in functional programming systems._
  Proc. of [.ordn]#12th# ACM [.acro]#SIGACT-SIGPLAN# symposium on Principles of Programming Languages.
  {scholar}hudak&title=the+aggregate+update+problem+in+functional+programming[search^]

* [[[Hudak-RC]]] Paul *Hudak* (1986) _A semantic model of reference counting and its abstraction._
  Record of ACM Symposium on LISP and Functional Programming Vol. 348.
  {scholar}hudak&title=a+semantic+model+of+reference+counting+and+its+abstraction[search^]

* [[[Hudak-History]]] Paul *Hudak* (1989) _Conception, evolution, and application of functional programming languages._
  ACM Computing Surveys 21.3.
  {scholar}hudak&title=conception+evolution+and+application+of+functional+programming+languages[search^]

* [[[Hudak-FRP]]] Paul *Hudak* et al. (2002) _Arrows, robots, and functional reactive programming._
  Intl. School on Advanced Functional Programming. Springer, Berlin, Heidelberg.
  {scholar}hudak&title=arrows+robots+and+functional+reactive+programming[search^]

* [[[Huddleston-Robust]]] Scott *Huddleston* and Kurt *Mehlhorn* (1981) _Robust balancing in B-trees._
  Theoretical Computer Science. Springer, Berlin, Heidelberg.
  {scholar}huddleston&title=robust+balancing+in+b+trees[search^]

* [[[Huddleston-Weak]]] Scott *Huddleston* and Kurt *Mehlhorn* (1982)
  _A new data structure for representing sorted lists._ Acta Informatica 17.2.
  {scholar}huddleston&title=a+new+data+structure+for+representing+sorted+lists[search^]

* [[[Hughes-GC]]] John *Hughes* (1985) _A distributed garbage collection algorithm._
  Conf. on Functional Programming Languages and Computer Architecture. Springer, Berlin, Heidelberg.
  {scholar}hughes&title=a+distributed+garbage+collection+algorithm[search^]

* [[[Hughes-Why]]] John *Hughes* (1989) _Why functional programming matters._ The Computer Journal 32.2.
  {scholar}hughes&title=why+functional+programming+matters[search^]

[[bib-i]]
* [[[Squeak]]] Dan *Ingalls* et al. (1997)
  _Back to the future: the story of [.caps]#Squeak#, a practical [.caps]#Smalltalk# written in itself._
  ACM [.acro]#SIGPLAN# Notices 32.10.
  {scholar}ingalls&title=back+to+the+future+the+story+of+squeak+a+practical+smalltalk[search^]

[[bib-j]]
* [[[Spooky]]] Bob *Jenkins* (2012) _[.caps]#SpookyHash#: a 128-bit noncryptographic hash._
  https://www.burtleburtle.net/bob/hash/spooky.html[source^]

[[bib-k]]
* [[[Kaplan-Thesis]]] Haim *Kaplan* (1997) _Purely functional lists._
  Doctoral thesis, Adviser Bob *Tarjan*, Princeton University.
  {scholar}kaplan&title=purely+functional+lists[search^]

* [[[Kaplan-Survey]]] Haim *Kaplan* (2001) _Persistent data structures._
  Handbook on Data Structures and Applications, Editors Sartaj Sahni and Dinesh Mehta, CRC Press.
  https://www.google.com/books/edition/Handbook_of_Data_Structures_and_Applicat/fQVZy1zcpJkC[search^]

* [[[Personal-Computer]]] Alan *Kay* (1972) _A personal computer for children of all ages._
  Proc. of ACM Annual Conf. Vol. 1.
  {scholar}kay&title=a+personal+computer+for+children+of+all+ages[search^]

* [[[Kay-Twenty]]] Alan *Kay* (1975) _Personal Computing._
  Meeting on 20 Years of Computing Science, Instituto di Elaborazione della Informazione, Pisa, Italy.
  https://mprove.de/visionreality/media/kay.html[source^]

* [[[Kay-Media]]] Alan *Kay* and Adele *Goldberg* (1977) _Personal dynamic media._ Computer 3.
  {scholar}kay&title=personal+dynamic+media[search^]

* [[[Smalltalk-History]]] Alan *Kay* (1996) _The early history of [.caps]#Smalltalk#._
  History of Programming Languages II, ACM.
  {scholar}kay&title=the+early+history+of+smalltalk[search^]

* [[[Kay-OO]]] Alan *Kay* (2003) _Meaning of Object-Oriented Programming._
  Private email exchange with Stefan Ram.
  http://www.purl.org/stefan_ram/pub/doc_kay_oop_en[source^]

* [[[Keller-Lindstrom]]] Robert *Keller* and Gary *Lindstrom* (1985)
  _Approaching Distributed Database Implementations Through Functional Programming Concepts._
  Proc. of [.ordn]#5th# Intl. Conf. on Distributed Computing Systems.
  {scholar}keller&title=approaching+distributed+database+implementations+through+functional+programming[search^]

* [[[Kernighan-Ritchie]]] Brian *Kernighan* and Dennis *Ritchie* (1978) _The C Programming Language._
  Prentice Hall.
  {scholar}kernighan&title=the+c+programming+language[search^]

* [[[Kleinberg-Tardos]]] Jon *Kleinberg* and Éva *Tardos* (2005) _Algorithm design._ Pearson Education.
  {scholar}kleinberg&title=algorithm+design[search^]

* [[[Kleppmann]]] Martin *Kleppmann* (2017) _Designing Data-Intensive Applications._
  O'Reilly Media.
  https://www.google.com/books/edition/Designing_Data_Intensive_Applications/p1heDgAAQBAJ[search^]

* [[[Timestamp]]] Graham *Klyne* and C. *Newman* (2002) _Date and Time on the Internet: Timestamps._
  RFC 3339, [.acro]#DOI 10.17487/RFC3339#. {rfc}3339[source^]

* [[[Knuth]]] Donald *Knuth* (1973) _The Art of Computer Programming (Vol. 3) Sorting and Searching._
  Addison-Wesley, Reading MA.
  {scholar}knuth&title=the+art+of+computer+programming[search^]

[[bib-l]]
* [[[Lamport-Time]]] Leslie *Lamport* (1978) _Time, clocks, and the ordering of events in a distributed system._
  Comm. of ACM 21.7.
  {scholar}lamport&title=time+clocks+and+the+ordering+of+events[search^]

* [[[Lamport-Write]]] Leslie *Lamport* (1995) _How to write a proof._
  The American Mathematical Monthly 102.7.
  {scholar}lamport&title=how+to+write+a+proof[search^]

* [[[Landauer]]] Walter *Landauer* (1963) _The balanced tree and its utilization in information retrieval._
  IEEE Transactions on Electronic Computers 6.
  {scholar}landauer&title=the+balanced+tree+and+its+utilization+in+information+retrieval[search^]

* [[[Landin-Eval]]] Peter *Landin* (1964) _The mechanical evaluation of expressions._
  The Computer Journal 6.4.
  {scholar}landin&title=the+mechanical+evaluation+of+expressions[search^]

* [[[Landin-Next]]] Peter *Landin* (1966) _The next 700 programming languages._
  Comm. of ACM 9.3.
  {scholar}landin&title=the+next+700+programming+languages[search^]

* [[[Larson-Linear]]] Per-Åke *Larson* (1980) _Linear hashing with partial expansions._
  Proc. of [.ordn]#6th# Intl. Conf. on Very Large Data Bases, Volume 6, VLDB Endowment.
  {scholar}larson&title=linear+hashing+with+partial+expansions[search^]

* [[[Larson-Dynamic]]] Per-Åke *Larson* (1988) _Dynamic Hash Tables._
  Comm. of ACM 31.4.
  {scholar}larson&title=dynamic+hash+tables[search^]

* [[[UUID]]] Paul *Leach*, Michael *Mealling* and Rich *Salz* (2005)
  _[.acro]#UUID#: A Universally Unique IDentifier URN Namespace._
  RFC 4122, [.acro]#DOI 10.17487/RFC4122#. {rfc}4122[source^]

* [[[Liljenzin]]] Olle *Liljenzin* (2013) _Confluently Persistent Sets and Maps._ arXiv preprint [.caps]#arXiv:1301.3388#.
  {scholar}liljenzin&title=confluently+persistent+sets+and+maps[search^]

* [[[Liskov]]] Barbara *Liskov* and Stephen *Zilles* (1974) _Programming with abstract data types._
  ACM [.acro]#SIGPLAN# Notices 9.4.
  {scholar}liskov&title=programming+with+abstract+data+types[search^]

* [[[Litwin-Linear]]] Witold *Litwin* (1980) _Linear hashing: a new tool for file and table addressing._
  [.acro]#VLDB# Vol. 80.
  {scholar}litwin&title=linear+hashing+a+new+tool+for+file+and+table+addressing[search^]

* [[[Litwin-Trie]]] Witold *Litwin* (1981) _Trie hashing._
  Proc. of ACM [.acro]#SIGMOD# Intl. Conf. on Management of Data.
  {scholar}litwin&title=trie+hashing[search^]

* [[[Lomet-Multiversion]]] David *Lomet* and Betty *Salzberg* (1989)
  _Access methods for multiversion data._ Comm. of ACM 18.2.
  {scholar}lomet&title=access+methods+for+multiversion+data[search^]

* [[[Lorange]]] Jean Niklas *L'orange* (2014) _Improving RRB-Tree Performance through Transience._
  Master thesis, Norwegian University of Science and Technology.
  {scholar}lorange&title=improving+rrb+tree+performance+through+transience[search^]

[[bib-m]]
* [[[MacLennan-Values]]] Bruce *MacLennan* (1981) _Values and Objects in Programming Languages._
  Technical Report [.acro]#NPS52-81-006#. Naval Postgraduate School, Monterey CA.
  {scholar}maclennan&title=values+and+objects+in+programming+languages[search^]

* [[[MacLennan-OO]]] Bruce *MacLennan* (1983) _A View of Object-Oriented Programming._
  Technical Report [.acro]#NPS52-83-001#. Naval Postgraduate School, Monterey CA.
  {scholar}maclennan&title=a+view+of+object+oriented+programming[search^]

* [[[Maier]]] David *Maier* and Sharon *Salveter* (1981) _Hysterical B-trees._
  Information Processing Letters 12.4.
  {scholar}maier&title=hysterical+b+trees[search^]

* [[[Manegold]]] Stefan *Manegold*, Peter *Boncz* and Martin *Kersten* (2000)
  _Optimizing database architecture for the new bottleneck: memory access._
  [.acro]#VLDB# 9.3.
  {scholar}manegold&title=optimizing+database+architecture+for+the+new+bottleneck+memory+access[search^]

* [[[Marsaglia-Normal]]] George *Marsaglia* and Thomas *Bray* (1964)
  _A convenient method for generating normal variables._ SIAM Review 6.3.
  {scholar}marsaglia&title=a+convenient+method+for+generating+normal+variables[search^]

* [[[Xorshift]]] George *Marsaglia* (2003) _Xorshift RNGs._ Journal of Statistical Software 8.14.
  {scholar}marsaglia&title=xorshift+rngs[search^]

* [[[Matsakis]]] Nicholas *Matsakis* (2018) _In Rust, ordinary vectors are values._ Blog, 1 Feb. 2018.
  https://www.smallcultfollowing.com/babysteps/blog/2018/02/01/in-rust-ordinary-vectors-are-values/[smallcultfollowing.com^]

* [[[LISP]]] John *McCarthy* (1960) _Recursive functions of symbolic expressions and their computation by machine._
  Comm. of ACM 3.4.
  {scholar}mccarthy&title=recursive+functions+of+symbolic+expressions[search^]

* [[[McCarthy-Linking]]] John *McCarthy*, Fernando *Corbató* and Marjorie *Daggett* (1963)
  _The Linking Segment Subprogram Language and Linking Loader._ Comm. of ACM 6.7.
  {scholar}mccarthy&title=the+linking+segment+subprogram+language+and+linking+loader[search^]

* [[[LISP-History]]] John *McCarthy* (1978) _History of LISP._ ACM [.acro]#SIGPLAN# Notices 13.8.
  {scholar}mccarthy&title=history+of+lisp[search^]

* [[[Meijer]]] Erik *Meijer*, Maarten *Fokkinga* and Ross *Paterson* (1991)
  _Functional programming with bananas, lenses, envelopes and barbed wire._
  Conf. on Functional Programming Languages and Computer Architecture. Springer, Berlin, Heidelberg.
  {scholar}meijer&title=functional+programming+with+bananas+lenses+envelopes+and+barbed+wire[search^]

* [[[Milner]]] Robin *Milner* (1982) _How ML evolved_ ML/Hope/LCF Newsletter 1.1.
  https://www.research.ed.ac.uk/portal/en/publications/how-ml-evlolved(86317c55-fb0d-4103-aa78-b5a97e93c1c6).html[source^]

* [[[DNS]]] Paul *Mockapetris* (1987) _Domain names--concepts and facilities._
  STD 13, RFC 1034, [.acro]#DOI 10.17487/RFC1034#. {rfc}1034[source^]

* [[[Moore]]] Gordon *Moore* (1965) _Cramming more components onto integrated circuits._
  Electronics 38.8.
  {scholar}moore&title=cramming+more+components+onto+integrated+circuits[search^]

* [[[Morrison]]] J. Paul *Morrison* (1971) _Data responsive modular, interleaved task programming system._
  IBM Technical Disclosure Bulletin 13.8.
  {scholar}morrison&title=data+responsive+modular+interleaved+task+programming+system[search^]

* [[[Moseley-Marks]]] Ben *Moseley* and Peter *Marks* (2006) _Out of the tar pit._
  Software Practice Advancement.
  {scholar}moseley&title=out+of+the+tar+pit[search^]

* [[[Myers]]] Eugene *Myers* (1984) _Efficient applicative data types._ POPL Vol. 84.
  {scholar}myers&title=efficient+applicative+data+types[search^]

[[bib-n]]
* [[[Newell-Process]]] Allen *Newell* and Herbert *Simon* (1956)
  _The logic theory machine: a complex information processing system._
  IRE Transactions on Information Theory 2.3.
  {scholar}newell&title=the+logic+theory+machine+a+complex+information+processing+system[search^]

* [[[Newell-Machine]]] Allen *Newell*, John Clark *Shaw* and Herbert *Simon* (1957)
  _Empirical explorations of the logic theory machine: a case study in heuristic._
  Western Joint Computer Conf. Techniques for Reliability, ACM.
  {scholar}newell&title=empirical+explorations+of+the+logic+theory+machine[search^]

* [[[Newell-Solving]]] Allen *Newell*, John Clark *Shaw* and Herbert *Simon* (1959)
  _Report on a general problem solving program._ IFIP Congress, Vol. 256.
  {scholar}newell&title=report+on+a+general+problem+solving+program[search^]

* [[[Nicklas]]] B. M. *Nicklas* and Gunter *Schlageter* (1977)
  _Index structuring in inverted data bases by [.acro]#TRIES#._ The Computer Journal 20.4.
  {scholar}nicklas&title=index+structuring+in+inverted+data+bases+by+tries[search^]

* [[[Nikhil-Dataflow]]] Rishiyur *Nikhil* (1989) _Can dataflow subsume von Neumann computing?_
  ACM [.acro]#SIGARCH# 17.3.
  {scholar}nikhil&title=can+dataflow+subsume+von+neumann+computing[search^]

* [[[Nikhil-Structures]]] Rishiyur *Nikhil* and Keshav *Pingali* (1989)
  _I-structures: Data structures for parallel computing._
  ACM Transactions on Programming Languages and Systems 11.4.
  {scholar}nikhil&title=data+structures+for+parallel+computing[search^]

* [[[Noble]]] James *Noble*, Jan *Vitek* and John *Potter* (1998) _Flexible alias protection._
  European Conf. on Object-Oriented Programming. Springer, Berlin, Heidelberg.
  {scholar}noble&title=flexible+alias+protection[search^]

[[bib-o]]
* [[[Odersky-Destructive]]] Martin *Odersky* (1991) _How to make destructive updates less destructive._ POPL Vol. 91.
  {scholar}odersky&title=how+to+make+destructive+updates+less+destructive[search^]

* [[[Odersky-Observers]]] Martin *Odersky* (1992) _Observers for linear types._
  European Symposium on Programming. Springer, Berlin, Heidelberg.
  {scholar}odersky&title=observers+for+linear+types[search^]

* [[[Okasaki]]] Chris *Okasaki* (1999) _Purely functional data structures._ Cambridge University Press.
  {scholar}okasaki&title=purely+functional+data+structures[search^]

* [[[ONeill-Thesis]]] Melissa E. *O'Neill* (1994)
  _A data structure for more efficient runtime support of truly functional arrays._
  Master thesis, Simon Fraser University, British Columbia.
  {scholar}oneill&title=a+data+structure+for+more+efficient+runtime+support+of+truly+functional+arrays[search^]

* [[[ONeill-Array]]] Melissa *O'Neill* and F. Warren *Burton* (1997) _A new method for functional arrays._
  Journal of Functional Programming 7.5.
  {scholar}oneill&title=a+new+method+for+functional+arrays[search^]

* [[[LSM-Tree]]] Patrick *O’Neil*, Edward *Cheng*, Dieter *Gawlick* and Elizabeth *O’Neil* (1996)
  _The [.caps]#LSM-Tree# log-structured merge-tree._ Acta Informatica 33.4.
  {scholar}oneill&title=the+log+structured+merge+tree[search^]

* [[[Raft-Consensus]]] Diego *Ongaro* and John *Ousterhout* (2014) _In search of an understandable consensus algorithm._
  Proc. of 2014 [.acro]#USENIX# Conf, [.acro]#USENIX# Assoc.
  {scholar}ongaro&title=in+search+of+an+understandable+consensus+algorithm[search^]

[[bib-p]]
* [[[Parnas-Modules]]] David *Parnas* (1972) _On the criteria to be used in decomposing systems into modules._
  Comm. of ACM 15.12.
  {scholar}parnas&title=on+the+criteria+to+be+used+in+decomposing+systems+into+modules[search^]

* [[[Parnas-Aging]]] David *Parnas* (1994) _Software aging._
  Proc. of [.ordn]#16th# Intl. Conf. on Software Engineering, IEEE.
  {scholar}parnas&title=software+aging[search^]

* [[[Perlis-Symbol]]] Alan *Perlis* and Charles *Thornton* (1960) _Symbol manipulation by threaded lists._
  Comm. of ACM 3.4.
  {scholar}perlis&title=symbol+manipulation+by+threaded+lists[search^]

* [[[Perlis-Synthesis]]] Alan *Perlis* (1967) _The synthesis of algorithmic systems._
  Journal of ACM 14.1.
  {scholar}perlis&title=the+synthesis+of+algorithmic+systems[search^]

* [[[Pike-Stanford]]] Rob *Pike* (2010) _Another Go at Language Design._
  Invited talk at Stanford Univ. 80 mins, https://youtu.be/7VcArS4Wpqk[watch^].

* [[[Pike-Concurrency]]] Rob *Pike* (2012) _Concurrency is Not Parallelism._
  Heroku. 30 mins, https://vimeo.com/49718712[watch^].

* [[[Polya]]] George *Polya* (1945) _How To Solve It: A New Aspect of Mathematical Method._ Princeton University Press.
  https://www.google.com/books/edition/How_to_Solve_It/X3xsgXjTGgoC[search^]

* [[[UDP]]] Jon *Postel* (1980) _User Datagram Protocol._
  STD 6, RFC 768, [.acro]#DOI 10.17487/RFC0768#. {rfc}768[source^]

* [[[IP]]] Jon *Postel* (1981) _Internet Protocol._
  STD 5, RFC 791, [.acro]#DOI 10.17487/RFC0791#. {rfc}791[source^]

* [[[TCP]]] Jon *Postel* (1981) _Transmission Control Protocol._
  STD 7, RFC 793, [.acro]#DOI 10.17487/RFC0793#. {rfc}793[source^]

* [[[Puente]]] Juan Pedro Bolívar *Puente* (2017) _Persistence for the masses: RRB-vectors in a systems language._
  Proc. of ACM on Programming Languages 1, ICFP 16.
  {scholar}puente&title=persistence+for+the+masses[search^]

* [[[Punched-Card-Equipment]]] Emerson *Pugh* and Lars *Heide* (2013) _Early punched card equipment: 1880-1951._
  Proc. of IEEE 101.2.
  {scholar}pugh&title=early+punched+card+equipment[search^]

* [[[Skip-List]]] William *Pugh* (1990) _Skip lists: a probabilistic alternative to balanced trees._
  Comm. of ACM 33.6.
  {scholar}pugh&title=skip+lists+a+probabilistic+alternative+to+balanced+trees[search^]

[[bib-r]]
* [[[GEDANKEN]]] John *Reynolds* (1970)
  _[.acro]#GEDANKEN#: a simple typeless language based on the principle of completeness and the reference concept._
  Comm. of ACM 13.5.
  {scholar}reynolds&title=gedanken+a+simple+typeless+language+based+on+the+principle+of+completeness[search^]

* [[[Reynolds-Definitional]]] John *Reynolds* (1972) _Definitional interpreters for higher-order programming languages._
  Proc. of ACM Annual Conf. Vol. 2.
  {scholar}reynolds&title=definitional+interpreters+for+higher+order+programming+languages[search^]

* [[[UNIX]]] Dennis *Ritchie* and Ken *Thompson* (1978) _The [.acro]#UNIX# time‐sharing system._
  Bell System Technical Journal 57.6.
  {scholar}ritchie&title=the+unix+time+sharing+system[search^]

* [[[MD5]]] Ronald *Rivest* (1992) _The [.acro]#MD5# Message-Digest Algorithm._
  RFC 1321, [.acro]#DOI 10.17487/RFC1321#. {rfc}1321[source^]

* [[[Rosenblum-Ousterhout]]] Mendel *Rosenblum* and John *Ousterhout* (1992)
  _The design and implementation of a log-structured file system._
  ACM Transactions on Computer Systems 10.1.
  {scholar}rosenblum&title=the+design+and+implementation+of+a+log+structured+file+system[search^]

[[bib-s]]
* [[[Sarnak-Thesis]]] Neil Ivor *Sarnak* (1986) _Persistent data structures._
  Doctoral thesis, Adviser Bob *Tarjan*, New York University.
  {scholar}sarnak&title=persistent+data+structures[search^]

* [[[Schorr-Waite]]] Herbert *Schorr* and William *Waite* (1967)
  _An efficient machine-independent procedure for garbage collection in various list structures._
  Comm. of ACM 10.8.
  {scholar}schorr&title=an+efficient+machine+independent+procedure+for+garbage+collection[search^]

* [[[Scott-Theory]]] Dana *Scott* (1970) _Outline of a mathematical theory of computation._
  Programming Research Group, Oxford University Computing Laboratory.
  {scholar}scott&title=outline+of+a+mathematical+theory+of+computation[search^]

* [[[Treap]]] Raimund *Seidel* and Cecilia *Aragon* (1996) _Randomized search trees._
  Algorithmica 16.4.
  {scholar}seidel&title=randomized+search+trees[search^]

* [[[Sen-Tarjan]]] Siddhartha *Sen* and Robert *Tarjan* (2009) _Deletion without rebalancing in multiway search trees._
  Intl. Symposium on Algorithms and Computation. Springer, Berlin, Heidelberg.
  {scholar}sen&title=deletion+without+rebalancing+in+multiway+search+trees[search^]

* [[[Shamir-Share]]] Adi *Shamir* (1979) _How to share a secret._ Comm. of ACM 22.11.
  {scholar}shamir&title=how+to+share+a+secret[search^]

* [[[Shao-Appel]]] Zhong *Shao* and Andrew *Appel* (1994)
  _Space-efficient closure representations._ Comm. of ACM 7.3.
  {scholar}shao&title=space+efficient+closure+representations[search^]

* [[[Shaw-Processing]]] John Clark *Shaw*, Allen *Newell*, Herbert *Simon* and T. O. *Ellis* (1958)
  _A command structure for complex information processing._
  Western Joint Computer Conf. Contrasts in Computers, ACM.
  {scholar}shaw&title=a+command+structure+for+complex+information+processing[search^]

* [[[Shoup]]] Victor *Shoup* (2009) _A Computational Introduction to Number Theory and Algebra._
  Cambridge University Press.
  {scholar}shoup&title=a+computational+introduction+to+number+theory[search^]

* [[[Splay-Tree]]] Daniel *Sleator* and Robert *Tarjan* (1985) _Self-Adjusting Binary Search Trees._
  Journal of ACM 32.3.
  {scholar}sleator&title=self+adjusting+binary+search+trees[search^]

* [[[Smith-Alias]]] Frederick *Smith*, David *Walker* and Greg *Morrisett* (2000) _Alias types._
  European Symposium on Programming. Springer, Berlin, Heidelberg.
  {scholar}smith&title=alias+types[search^]

* [[[Steele-GC]]] Guy Lewis *Steele* Jr. (1975) _Multiprocessing compactifying garbage collection._
  Comm. of ACM 18.9.
  {scholar}steele&title=multiprocessing+compactifying+garbage+collection[search^]

* [[[Lambda-the-Ultimate]]] Guy *Steele* and Gerald *Sussman* (1976) _Lambda: The ultimate imperative._
  Technical Report [.acro]#AI-M-353#. MIT AI Lab, Cambridge MA.
  {scholar}steele&title=lambda+the+ultimate+imperative[search^]

* [[[Steele-Data]]] Guy *Steele* (1977) _Data Representations in PDP-10 [.caps]#MacLISP#._
  Technical Report [.acro]#AI-M-420#. MIT AI Lab, Cambridge MA.
  {scholar}steele&title=data+representations+in+pdp+10+maclisp[search^]

* [[[Steele-Arithmetic]]] Guy *Steele* (1977) _Fast Arithmetic in [.caps]#MacLISP#._
  Technical Report [.acro]#AI-M-421#. MIT AI Lab, Cambridge MA.
  {scholar}steele&title=fast+arithmetic+in+maclisp[search^]

* [[[Rabbit]]] Guy *Steele* (1978) _[.caps]#Rabbit#: A compiler for [.caps]#Scheme#._
  Technical Report [.acro]#AI-M-474#. MIT AI Lab, Cambridge MA.
  {scholar}steele&title=rabbit+a+compiler+for+scheme[search^]

* [[[Steele-Lazy]]] Guy *Steele* and Gerald *Sussman* (1980)
  _The dream of a lifetime: A lazy variable extent mechanism._
  Proc. of ACM Conf. on LISP and Functional Programming.
  {scholar}steele&title=the+dream+of+a+lifetime[search^]

* [[[Steele-Print]]] Guy *Steele* and Jon *White* (1990) _How to print floating-point numbers accurately._
  ACM [.acro]#SIGPLAN# Notices 25.6.
  {scholar}steele&title=how+to+print+floating+point+numbers+accurately[search^]

* [[[Steindorfer-HAMT]]] Michael *Steindorfer* and Jurgen *Vinju* (2015)
  _Optimizing hash-array mapped tries for fast and lean immutable JVM collections._
  ACM [.acro]#SIGPLAN# Notices 50.10.
  {scholar}steindorfer&title=optimizing+hash+array+mapped+tries+for+fast+and+lean+immutable[search^]

* [[[Steindorfer-Thesis]]] Michael J. *Steindorfer* (2017) _Efficient immutable collections._
  Doctoral Thesis, University of Amsterdam, Netherlands.
  {scholar}steindorfer&title=efficient+immutable+collections[search^]

* [[[Stucki]]] Nicolas *Stucki* et al. (2015) _RRB vector: a practical general purpose immutable sequence._
  ACM [.acro]#SIGPLAN# Notices 50.9.
  {scholar}stucki&title=rrb+vector[search^]

* [[[Scheme]]] Gerald *Sussman* and Guy *Steele* (1975) _[.caps]#Scheme#: an interpreter for extended lambda calculus._
  Technical Report [.acro]#AI-M-349#. MIT AI Lab, Cambridge MA.
  {scholar}sussman&title=scheme+a+interpreter+for+extended+lambda+calculus[search^]

* [[[Swartout-Balzer]]] William *Swartout* and Robert *Balzer* (1982)
  _On the inevitable intertwining of specification and implementation._
  Comm. of ACM 25.7.
  {scholar}swartout&title=on+the+inevitable+intertwining+of+specification+and+implementation[search^]

[[bib-t]]
* [[[Tamminen]]] Markku *Tamminen* (1981) _Order preserving extendible hashing and bucket tries._
  BIT Numerical Mathematics 21.4.
  {scholar}tamminen&title=order+preserving+extendible+hashing+and+bucket+tries[search^]

* [[[Amortized]]] Robert *Tarjan* (1985) _Amortized computational complexity._
  SIAM Journal on Algebraic Discrete Methods 6.2.
  {scholar}tarjan&title=amortized+computational+complexity[search^]

* [[[Tene-GC]]] Gil *Tene* (2012) _Understanding Java Garbage Collection._
  SpringOne. 90 mins, https://youtu.be/we_enrM7TSY[watch^].

* [[[Thompson-Trust]]] Ken *Thompson* (1984) _Reflections on trusting trust._ Comm. of ACM 27.8.
  {scholar}thompson&title=reflections+on+trusting+trust[search^], see <<UNIX>>

* [[[TIOBE]]] [.acro]#TIOBE# Index (2019)
  https://www.tiobe.com/tiobe-index/[tiobe.com^]

* [[[Turner-Applicative]]] David *Turner* (1979) _A New Implementation Technique for Applicative Languages._
  Software Practice and Experience 9.1.
  {scholar}turner&title=a+new+implementation+technique+for+applicative+languages[search^]

* [[[Turner-Recursion]]] David *Turner* (1982) _Recursion Equations as a Programming Language._
  A List of Successes That Can Change the World. Springer, Cham.
  {scholar}turner&title=recursion+equations+as+a+programming+language[search^]

[[bib-u]]
* [[[SELF]]] David *Ungar* and Randall *Smith* (1991)
  _[.acro]##SELF##: the Power of Simplicity._ Lisp and Symbolic Computing 4.3.
  {scholar}ungar&title=self+the+power+of+simplicity[search^]

[[bib-v]]
* [[[EDVAC]]] John *von Neumann* (1945) _First Draft of a Report on the [.acro]#EDVAC#._
  Univ. of Pennsylvania.
  {scholar}von+neumann&title=first+draft+of+a+report+on+the+edvac[search^]

* [[[Merge-Sort]]] John *von Neumann* and Herman *Goldstine* (1948)
  _Planning and coding of problems for an electronic computing instrument._
  Institute for Advanced Study, Princeton NJ.
  {scholar}von+neumann&title=planning+and+coding+of+problems+for+an+electronic+computing+instrument[search^]

* [[[Python]]] Guido *Van Rossum* and Fred *Drake* Jr (1995) [.caps]#Python# reference manual.
  Amsterdam: Centrum voor Wiskunde en Informatica.
  {scholar}van+rossum&title=python+reference+manual[search^],
  https://www.python.org/[python.org^]

* [[[Vanderburg]]] Glenn *Vanderburg* (2012) _Real Software Engineering._
  Keynote Address Nov. 7, QCon San Francisco, Hyatt Regency San Francisco, InfoQ.
  https://www.infoq.com/presentations/Software-Engineering[infoq.com^] --
  https://qconsf.com/sf2012/dl/qcon-sanfran-2012/slides/GlennVanderburg_OpeningKeynoteRealSoftwareEngineering.pdf[slides^]

[[bib-w]]
* [[[Wadler-Linear]]] Philip *Wadler* (1990) _Linear types can change the world!_
  Programming Concepts and Methods, Vol. 3.4.
  {scholar}wadler&title=linear+types+can+change+the+world[search^]

* [[[Wadler-Essence]]] Philip *Wadler* (1992) _The essence of functional programming._ POPL Vol. 92.37.
  {scholar}wadler&title=the+essence+of+functional+programming[search^]

* [[[Wadler-Imperative]]] Philip *Wadler* and Simon *Peyton Jones* (1993) _Imperative functional programming._
  Proc. of [.ordn]#20th# Annual ACM [.acro]#SIGACT-SIGPLAN# Symposium on Principles of Programming Languages.
  {scholar}wadler&title=imperative+functional+programming[search^]

* [[[Wakeling]]] David *Wakeling* and Colin *Runciman* (1991) _Linearity and laziness._
  Conf. on Functional Programming Languages and Computer Architecture. Springer, Berlin, Heidelberg.
  {scholar}wakeling&title=linearity+and+laziness[search^]

* [[[Hackers-Delight]]] Henry *Warren* (2002) _Hacker's Delight._ Pearson Education.
  https://www.google.com/books/edition/Hacker_s_Delight/VicPJYM0I5QC[search^]

* [[[Weiss]]] Aaron *Weiss*, Daniel *Patterson*, Nicholas *Matsakis* and Amal *Ahmed* (2019)
  _Oxide: The Essence of Rust._ arXiv preprint [.caps]#arXiv:1903.00982#.
  {scholar}weiss&title=oxide+the+essence+of+rust[search^]

* [[[Weizenbaum-Knotted]]] Joseph *Weizenbaum* (1961) _Knotted list structures._
  Proc. of [.ordn]#16th# ACM National Meeting.
  {scholar}weizenbaum&title=knotted+list+structures[search^]
+
"(This scheme) permits a sub-list to be a sub-list of many lists."

* [[[Weizenbaum-Symmetric]]] Joseph *Weizenbaum* (1963) _Symmetric list processor._ Comm. of ACM 6.9.
  {scholar}weizenbaum&title=symmetric+list+processor[search^]

* [[[Subroutine]]] David *Wheeler* (1952) _The use of sub-routines in programmes._
  Proc. of ACM national meeting, Pittsburgh. ACM, New York NY.
  {scholar}wheeler&title=the+use+of+sub+routines+in+programmes[search^], see <<Burrows-Wheeler>>

* [[[Whiting-History]]] Paul *Whiting* and Robert *Pascoe* (1994) _A history of data-flow languages._
  IEEE Annals of the History of Computing 16.4.
  {scholar}whiting&title=a+history+of+data+flow+languages[search^]

* [[[EDSAC]]] Maurice *Wilkes* and W. *Renwick* (1950)
  _The [.acro]#EDSAC#: Electronic Delay Storage Automatic Calculator._ Mathematics of Computation 4.30.
  {scholar}wilkes&title=the+edsac+electronic+delay+storage+automatic+calculator[search^]

* [[[Wilkes-Lists]]] Maurice *Wilkes* (1965) _Lists and why they are useful._ The Computer Journal 7.4.
  {scholar}wilkes&title=lists+and+why+they+are+useful[search^]

* [[[Wilkes-Pioneer]]] Maurice *Wilkes* (1985) _Memoirs of a computer pioneer._ MIT Press.
  {scholar}wilkes&title=memoirs+of+a+computer+pioneer[search^]
+
"The realization came over me with full force that a good part of the remainder of my life was going
to be _spent in finding errors in my own programs._"

* [[[Wilson-GC]]] Paul *Wilson* (1992) _Uniprocessor garbage collection techniques._
  Intl. Workshop on Memory Management. Springer, Berlin, Heidelberg.
  {scholar}wilson&title=uniprocessor+garbage+collection+techniques[search^]

* [[[Wilson-Malloc]]] Paul *Wilson* et al. (1995) _Dynamic storage allocation: A survey and critical review._
  Intl. Workshop on Memory Management. Springer, Berlin, Heidelberg.
  {scholar}wilson&title=dynamic+storage+allocation[search^]

[[bib-y]]
* [[[UTF-8]]] Francois *Yergeau* (2003) _UTF-8 -- a transformation format of ISO 10646._
  STD 63, RFC 3629, [.acro]#DOI 10.17487/RFC3629#. {rfc}3629[source^] https://en.wikipedia.org/wiki/UTF-8[wiki^]

