= image:logo/shield.svg[fress,47,link="./"] What's this fly doing in my coffee?
Cole Frederick
:revdate: July 23, 2021

There i was, absentmindedly sipping my coffee.
A fly buzzes by, I wave it away and refocus on the task at hand..

Without taking my eyes off the screen,
I lift the cup to my lips and take a sip.

Something solid, what's that?
I think back, trying to remember if I'd dropped part
of a cracker into this cup earlier in the day..

Crunch. Crunch.
I'm sad to say I took not one but two crunchy bites
before my attention came fully into focus on
the fact that I didn't have a cracker in my mouth.

It was a fly. A big one, with brilliant red multifaceted eyes.
It had died in the steaming hot coffee.
And I had been drinking steamed fly coffee.

I spit it out and threw it in the trash can, of course.
But I know what you're wondering; I was asking myself the same
question: should I drink the remaining fly coffee?

For what it's worth, I spent several minutes pining over
the decision. Both sides have merit. In the end,
I downed the cup; it really didn't taste any worse
for having a fly in it.

Was this karmic punishment for making half-caff at 9pm?
I'll never know; but I won't forget that distinctive
sensation.

